### ISSUE TITLE
Languages app is missing the Ulster Banner for Ireland

### ISSUE THREAD

**Issue by erterine** [linuxmint/mint19.2-beta#17]
Languages only displays the republic of ireland flag, not the Ulster Banner for English (Ireland)
My proposal is to make the flag split down diagonally to represent both equally as I do not Identify as british or irish, but northern irish as I was born in Ballymena, and I fell Mint is taking sides here.....
thank you for your consideration

![image](https://user-images.githubusercontent.com/53018418/61403921-967dda80-a893-11e9-8784-55f7e89678fd.png)

**Comment by erterine** [comment]
PS I'm not trying to start a fight, this is my legitimate concern

**Comment by clefebvre** [comment]
isn't the appropriate locale for ulster English (UK)? imperial units, pounds and all?

**Comment by clefebvre** [comment]
"English, United Kingdom" isn't "British" and the Union Jack doesn't just represent England or Great Britain, it represents the union as a whole, which Northern Ireland is a part of.

Using flags is always going to be a bit controversial because there's always a bit of politics or political interpretation involved. The locale for England, Ulster, Scotland and Wales is the exact same, it's English as a language and United Kingdom as a standard for units and currency.

The locale for Eire is different. Although the language is the same (English), the currency and units differ. You could make the point upstream to Debian that it should be called "English, Republic of Ireland" instead of "English, Ireland", but to be fair other countries don't use their official names either.

Here's an anecdote. I identify as being French and I bought a macbook in Ireland. Apple doesn't do Irish keyboards. My keyboard layout is thus "English, Mac" and because I use multiple layouts (I need to write into French at times), I've got that little union jack in my systray. Neither my nationality nor my country of residence are in the UK, but I did buy a computer with a UK keyboard.
