### ISSUE TITLE
Wrong default french keyboard

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint19.2-beta#20]
In MATE version, by default, the french keyboard is "Français - Français (variante obsolète)" instead of "Français - Français (variante)". We need to select "Français - Français (variante)" manually during the installation :
![Installation_2](https://user-images.githubusercontent.com/3955499/61409518-b1c40680-a8e2-11e9-9c91-bad86d7eaee1.png)

**Comment by clefebvre** [comment]
Alright so... there are three layouts at play here:

French (no variant): fr
French (variante): fr-oss
French (variante obsolete): fr-latin9

Which should be the default? Why variante, why not simply French? and based on what?

**Comment by clefebvre** [comment]
I only have one French laptop here and its keyboard layout is fr, not fr-oss. I happen to be in France right now. I guess I'll go shopping and look around at the keyboard layouts this afternoon. That'll beat any resources or rationale available online :)

**Comment by clefebvre** [comment]
Except for macbooks (which have their own layout), all the laptops and keyboards I could find were fr (i.e. without any variant). I'll use that as default then.

**Comment by clefebvre** [comment]
https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1807344

**Comment by InfoLibre** [comment]
My french keyboard is https://www.google.com/search?q=kb+g235&tbm=isch

On all the french computer I install Linux Mint, I choose French (French variante)

I test it with the key that is just under Echap. When I press it, I must obtain ² and when I press it + Shift, I must obtain ³.

$ cat /etc/default/keyboard

XKBMODEL="pc105"
XKBLAYOUT="fr"
XKBVARIANT="oss"
XKBOPTIONS=""

**Comment by InfoLibre** [comment]
In french : https://hotline.asdrad.com/selectionner_le_clavier_fr-oss

**Comment by clefebvre** [comment]
That's good, but the layout printed on the keyboards here is definitely fr, not fr-oss. You can tell by looking at the $ key, you should see the squary sign on most keyboards there as well.

**Comment by InfoLibre** [comment]
If I understood https://hotline.asdrad.com/selectionner_le_clavier_fr-oss, fr-oss is the same layout than fr but with a few more letters/signs. So, choosing fr-oss instead of fr is better, isn't it ?

**Comment by clefebvre** [comment]
It's not better by default no. Whether it's a better layout to type in French than fr or not is beside the point... if that was the question we'd need to convince keyboard manufacturers to adopt it before we set it as default in console-setup. The reality is, manufacturers adopted fr, so if you default to fr-oss, there are printed symbols on your keyboard keys which won't match your applied layout. Alt_gr + £ for instance differs between the two. That sign is printed on every keyboard I've seen in French shops.

I also need to close this issue because I think it should be fixed upstream. Not even at Ubuntu level, but reported to Debian directly. I can't fix it in Ubiquity alone and even with a patched console-setup it's hard to test in live mode because of the postinst affecting the behaviour of the installer.

This is a Debian bug in Debian's console-setup which probably affects all its derivatives. fr-latin9 should not be default, and neither should fr-oss. These two layouts may be better layouts than fr to type in French, but they do not correspond to what's printed on keyboards in France. I really think it's a mistake to not match manufacturer's choice. One might think it's an improvement, but if users are confused and don't take advantage of it, it certainly isn't.

**Comment by InfoLibre** [comment]
I don't remember which Linux it was, but one time near years 2000, I installed one that shows the different keyboards during the installation. The keyboards were drawn. I think it was a very good way to choose the right keyboard layout and variant.

**Comment by clefebvre** [comment]
We do that in our own installer (in LMDE). This is Ubuntu's ubiquity, we're a bit more restricted here.

**Comment by InfoLibre** [comment]
Thank you for this information. I will try the new LMDE. I more and more think it could be better for me because with Debian, more bugs could be solved (Ubuntu never solved only one of all the bugs I reported).
