### ISSUE TITLE
Add numlockx to default installation

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/mint19.2-beta#29]
**Describe the bug**
Feature request: Numlockx is not part of the default installation.

**To Reproduce**
Is it possible to add numlockx to the default installation? 
You have the option to enable numlock for loginscreen, but you can’t enable it without installing numlockx.

**Edition (Desktop environment):**
Mint 19.2 Cinnamon edition

**Comment by clefebvre** [comment]
We tried shipping it by default in the past. Feedback showed it created issues on some laptops and prevented people from logging (they couldn't type some of the letters on their keyboards because numlock turned them into numbers).

Looking at the package, it seems to still have the same issue. It's in auto mode by default and relies on laptop detection, which isn't always accurate. Installing it basically means risking affecting some sessions based on that detection.

**Comment by jakoblm** [comment]
Ok, thanks for the explanation.
