### ISSUE TITLE
mintupdate: no more changelog for itself

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/mint19.2-beta#32]
The update manager has nice infos about the changelog of every program which has updates available.
When a new mintupdate version can be installed, the new (and nice) layout prevents this information to be shown.

Workaround with apt changelog is possible, so this is no real problem...

**Comment by clefebvre** [comment]
hmm... that's a good point, I never really thought about that :)

I still think it's OK though. By design it wants to update itself prior to anything else and I think we want to keep that. We could show the changelog via a widget I guess... though I'm not sure it's really needed. That's an update you definitely have to go through, whatever changes it brings since it's your gateway to getting further updates.

**Comment by gm10** [comment]
If you're looking for inspiration:

![](https://user-images.githubusercontent.com/13855078/61554890-561e8800-aa5e-11e9-93a8-7a9de5aa595e.png)

(in a PPA near you :upside_down_face: - SCNR)

**Comment by Mintulix** [comment]
@gm10 I think you have too much time... :-D That was a quick one! Even if it was just mentioned for Clem.
Thanks a lot, I'll try this. But I hesitate to put a PPA (yours) on top of a PPA (alpha-testing), so I'll wait for the official release of LM 19.2.

**Comment by gm10** [comment]
@Mintulix oh that wasn't created in response to this issue, also unfortunately for you this is not something contributed to the official LM 19.2. 

My PPA is a fork and more than for official LM the need to show the changelog arose because I do weekly updates to Update Manager typically and I want the users to know what gets changed (I don't have a "What's new in LM 19.2" page for that).  That's also why the checkbox for automatic self-updates exist in my version. They become a bit of a nuisance if you keep them priority updates, which I agree with Clem on is still a good idea - the updater is at the core of the update strategy, you must ensure you can update it even when other updates fail, see the current gconf2 problems.

Official LM has a much slower rate of updating this application (ideally never outside of point releases), and the daily PPA builds have no changelog. So I also agree with Clem that there's no need for all that complexity in the official version. It was I who created the official version at the time actually, and I had considered the changelog question then and decided to keep it simple.

So I really only posted the screenshot for fun because it matched your request, didn't mean to cause confusion. :wink:

**Comment by Mintulix** [comment]
@gm10 All is fine, I meant "I'll wait for the official release of LM 19.2 - and test your PPA then". Teasing Clem caused no confusion, I wanted to try your versions of the mint-tools anyway ;-).
