### ISSUE TITLE
how to install firefox 3.0

### ISSUE THREAD

**Issue by erterine** [linuxmint/mint19.2-beta#34]
i just upgraded from ubuntu 7.10 and i do not like the new firefox, how do i go back to firefox 3.0

**Comment by brownsr** [comment]
You had a Ubuntu version from 2007 and a firefox version from 2008 ?  You are updating a computer that is around 10 years old or even more ? to a pre-release beta ?

**Comment by erterine** [comment]
yes this is my computer, why do I need to upgrade if it works fine, I try mint because mail.ie stopped working. 2007 was not long ago my friend Ive been using computers since I was in my 30s with the Sinclair zx80!

![5d30e3e8f3dbf](https://user-images.githubusercontent.com/53018418/61493405-bcc57800-a970-11e9-859c-844808b2ecbb.jpg)

**Comment by VaGNaroK** [comment]
WTF!! Ubuntu 7.10???

**Comment by cruftytheclown** [comment]
erterine, this is not a support forum. This is a place to report _bugs_ with the 19.2 beta. The support forums are here: http://forums.linuxmint.com/ 

And I think you should not have installed the 19.2 beta. The best version of Linux Mint for your old laptop is probably 18.3 XFCE. You should try it on a live cd first to see if it supports your hardware.

The reason you need to upgrade from an old unsupported OS is because it no longer receives security updates! Also, Firefox 3.0 is ancient and also doesn't receive security updates.
